"use client";

import { Alert, Box, Button, ButtonDropdown, Container, Header, KeyValuePairs, Link, Modal, Pagination, Select, SpaceBetween, StatusIndicator, Table, Tabs, TextFilter, type TableProps } from "@cloudscape-design/components";
import { useParams, useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { RecordForm } from "@/features/records/RecordForm";
import { BindImportModal } from "@/features/records/BindImportModal";
import { ApiClientError } from "@/lib/api/client";
import { hostedZonesApi, type HostedZoneDetail } from "@/lib/api/hostedZones";
import { recordsApi, recordTypes, type DnsRecord, type RecordType } from "@/lib/api/records";
import { useNotifications } from "@/providers/NotificationProvider";

const typeOptions = [{ label: "All record types", value: "" }, ...recordTypes.map((type) => ({ label: type, value: type }))];

export default function HostedZoneDetailPage() {
  const router = useRouter(); const params = useParams<{ zoneId: string }>(); const zoneId = params.zoneId; const { notify } = useNotifications();
  const [zone, setZone] = useState<HostedZoneDetail>(); const [records, setRecords] = useState<DnsRecord[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const [filteringText, setFilteringText] = useState(""); const [recordType, setRecordType] = useState(""); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState<string>();
  const [selected, setSelected] = useState<DnsRecord[]>([]); const [formRecord, setFormRecord] = useState<DnsRecord>(); const [showCreate, setShowCreate] = useState(false); const [showDelete, setShowDelete] = useState(false); const [showImport, setShowImport] = useState(false); const [isDeleting, setIsDeleting] = useState(false);
  const load = useCallback(async () => {
    setIsLoading(true); setError(undefined);
    try { const query = new URLSearchParams({ page: String(page), page_size: "20", sort_by: "name", sort_direction: "asc" }); if (filteringText) query.set("search", filteringText); if (recordType) query.set("type", recordType); const [zoneResponse, recordResponse] = await Promise.all([hostedZonesApi.get(zoneId), recordsApi.list(zoneId, query)]); setZone(zoneResponse); setRecords(recordResponse.items); setTotal(recordResponse.pagination.total); setSelected([]); }
    catch (caught) { setError(caught instanceof ApiClientError ? caught.message : "Unable to load the hosted zone."); }
    finally { setIsLoading(false); }
  }, [zoneId, page, filteringText, recordType]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const open = () => setShowCreate(true); window.addEventListener("route53:create-record", open); return () => window.removeEventListener("route53:create-record", open); }, []);
  const editableSelection = selected.length === 1 && !selected[0].is_system_record;
  async function bulkDelete() { if (!selected.length) return; setIsDeleting(true); try { const result = await recordsApi.bulkDelete(zoneId, selected.filter((record) => !record.is_system_record).map((record) => record.id)); setShowDelete(false); if (result.failed.length) notify({ type: "warning", content: `${result.deleted_ids.length} record(s) deleted; ${result.failed.length} could not be deleted.`, dismissLabel: "Dismiss notification" }); else notify({ type: "success", content: `${result.deleted_ids.length} record(s) deleted.`, dismissLabel: "Dismiss notification" }); await load(); } catch (caught) { notify({ type: "error", content: caught instanceof ApiClientError ? caught.message : "Unable to delete records.", dismissLabel: "Dismiss notification" }); } finally { setIsDeleting(false); } }
  async function exportZone(format: "json" | "bind") { try { const response = await recordsApi.export(zoneId, format); if (!response.ok) throw new Error("Export failed"); const content = await response.blob(); const url = URL.createObjectURL(content); const link = document.createElement("a"); link.href = url; link.download = `${zone?.name.replace(/\.$/, "") ?? "hosted-zone"}.${format === "bind" ? "zone" : "json"}`; link.click(); URL.revokeObjectURL(url); notify({ type: "success", content: `Hosted zone exported as ${format.toUpperCase()}.`, dismissLabel: "Dismiss notification" }); } catch { notify({ type: "error", content: "Unable to export this hosted zone.", dismissLabel: "Dismiss notification" }); } }
  const columns = useMemo<TableProps.ColumnDefinition<DnsRecord>[]>(() => [
    { id: "name", header: "Record name", cell: (record) => record.name, sortingField: "name" },
    { id: "type", header: "Type", cell: (record) => record.record_type },
    { id: "policy", header: "Routing policy", cell: (record) => record.routing_policy },
    { id: "differentiator", header: "Differentiator", cell: (record) => record.differentiator ?? "—" },
    { id: "alias", header: "Alias", cell: (record) => record.is_alias ? <StatusIndicator type="success">Yes</StatusIndicator> : "No" },
    { id: "value", header: "Value/Route traffic to", cell: (record) => record.alias_target ?? record.values.join(", ") },
    { id: "ttl", header: "TTL", cell: (record) => record.ttl ?? "—" },
    { id: "health", header: "Evaluate target health", cell: (record) => record.evaluate_target_health ? "Yes" : "No" },
    { id: "healthId", header: "Health check ID", cell: (record) => record.health_check_id ?? "—" },
    { id: "id", header: "Record ID", cell: (record) => record.id },
  ], []);
  const recordsTab = <SpaceBetween size="m"><Header variant="h2" actions={<SpaceBetween direction="horizontal" size="xs"><Button iconName="refresh" variant="icon" ariaLabel="Refresh records" onClick={() => void load()} /><Button disabled={!editableSelection} onClick={() => setFormRecord(selected[0])}>Edit record</Button><Button disabled={!selected.some((record) => !record.is_system_record)} onClick={() => setShowDelete(true)}>Delete record{selected.length > 1 ? "s" : ""}</Button><Button variant="primary" onClick={() => setShowCreate(true)}>Create record</Button></SpaceBetween>}>Records ({total})</Header><SpaceBetween direction="horizontal" size="s"><TextFilter filteringText={filteringText} filteringPlaceholder="Filter records by property or value" filteringAriaLabel="Filter records" onChange={({ detail }) => { setFilteringText(detail.filteringText); setPage(1); }} /><Select selectedOption={typeOptions.find((option) => option.value === recordType) ?? typeOptions[0]} options={typeOptions} onChange={({ detail }) => { setRecordType(detail.selectedOption.value ?? ""); setPage(1); }} /></SpaceBetween><Table items={records} loading={isLoading} loadingText="Loading records" selectionType="multi" trackBy="id" selectedItems={selected} onSelectionChange={({ detail }) => setSelected(detail.selectedItems)} columnDefinitions={columns} wrapLines empty={<Box textAlign="center" padding="xxl"><SpaceBetween size="m"><b>No records</b><Box color="text-body-secondary">Create a record to begin routing traffic for this hosted zone.</Box><Box><Button variant="primary" onClick={() => setShowCreate(true)}>Create record</Button></Box></SpaceBetween></Box>} footer={<Box textAlign="right"><Pagination currentPageIndex={page} pagesCount={Math.max(1, Math.ceil(total / 20))} onChange={({ detail }) => setPage(detail.currentPageIndex)} ariaLabels={{ nextPageLabel: "Next page", previousPageLabel: "Previous page", pageLabel: (number) => `Page ${number}` }} /></Box>} /></SpaceBetween>;
  const detailsTab = zone ? <Container header={<Header variant="h2">Hosted zone details</Header>}><KeyValuePairs columns={2} items={[{ label: "Hosted zone ID", value: zone.hosted_zone_id }, { label: "Type", value: zone.type === "PUBLIC" ? "Public hosted zone" : "Private hosted zone" }, { label: "Description", value: zone.description ?? "—" }, { label: "Record count", value: String(zone.record_count) }, { label: "Name servers", value: "Assigned automatically" }]} /></Container> : null;
  const tabs = [{ id: "records", label: "Records", content: recordsTab }, { id: "details", label: "Hosted zone details", content: detailsTab }, { id: "dnssec", label: "DNSSEC", content: <Container header={<Header variant="h2">DNSSEC signing</Header>}><StatusIndicator type="stopped">DNSSEC signing is disabled</StatusIndicator></Container> }, { id: "tags", label: "Tags", content: <Container header={<Header variant="h2">Tags</Header>}>{zone?.tags.length ? <KeyValuePairs columns={2} items={zone.tags.map((tag) => ({ label: tag.key, value: tag.value }))} /> : <Box color="text-body-secondary">No tags are associated with this hosted zone.</Box>}</Container> }];
  return <><SpaceBetween size="l"><Link onFollow={(event) => { event.preventDefault(); router.push("/hosted-zones"); }}>Hosted zones</Link><Header variant="h1" description={zone?.type === "PUBLIC" ? "Public hosted zone" : "Private hosted zone"} actions={<SpaceBetween direction="horizontal" size="xs"><ButtonDropdown items={[{ id: "import", text: "Import BIND zone file" }, { id: "json", text: "Export as JSON" }, { id: "bind", text: "Export as BIND" }]} onItemClick={({ detail }) => { if (detail.id === "import") setShowImport(true); if (detail.id === "json" || detail.id === "bind") void exportZone(detail.id); }}>Actions</ButtonDropdown><Button variant="primary" onClick={() => setShowCreate(true)}>Create record</Button></SpaceBetween>}>{zone?.name ?? "Hosted zone"}</Header>{error && <Alert type="error" action={<Button onClick={() => void load()}>Retry</Button>}>{error}</Alert>}<Tabs tabs={tabs} /></SpaceBetween>{zone && <><RecordForm zoneId={zoneId} zoneName={zone.name} visible={showCreate || Boolean(formRecord)} record={formRecord} onDismiss={() => { setShowCreate(false); setFormRecord(undefined); }} onSaved={(savedRecord, created) => { setShowCreate(false); setFormRecord(undefined); notify({ type: "success", content: `Record ${savedRecord.name} was ${created ? "created" : "updated"}.`, dismissLabel: "Dismiss notification" }); void load(); }} /><BindImportModal zoneId={zoneId} visible={showImport} onDismiss={() => setShowImport(false)} onImported={(count) => { setShowImport(false); notify({ type: "success", content: `${count} record(s) imported from BIND.`, dismissLabel: "Dismiss notification" }); void load(); }} /></>}<Modal visible={showDelete} onDismiss={() => setShowDelete(false)} header="Delete records" footer={<Box float="right"><SpaceBetween direction="horizontal" size="xs"><Button onClick={() => setShowDelete(false)}>Cancel</Button><Button variant="primary" loading={isDeleting} onClick={() => void bulkDelete()}>Delete</Button></SpaceBetween></Box>}><SpaceBetween size="m"><Alert type="warning">This action permanently deletes the selected record sets. Default NS and SOA records cannot be deleted.</Alert><Box>You are deleting {selected.filter((record) => !record.is_system_record).length} record{selected.filter((record) => !record.is_system_record).length === 1 ? "" : "s"}.</Box></SpaceBetween></Modal></>;
}
